security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        sudo:
            pattern: ^/sudo
            form_login:
                login_path: sudo_wh_user_security_login
                check_path: sudo_wh_user_security_logincheck
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: sudo_wh_user_security_logout
            anonymous:    true

        admin:
            pattern: ^/admin
            form_login:
                login_path: bk_wh_user_security_login
                check_path: bk_wh_user_security_logincheck
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: bk_wh_user_security_logout
            anonymous:    true

        main:
            anonymous: ~

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sudo/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/sudo/, role: ROLE_SUPER_ADMIN }
