title: 'Create a page'

formFields:
    - name
    - pageTemplateSlug
    - parent

footerFormFields:
    create:
        label: 'Create'
        field: 'create'
        color: 'success'
    createEdit:
        label: 'Create & Edit'
        field: 'createEdit'