tree: 'true'

title: 'Pages list'

breadcrumb:
    index:
        label: 'Pages list'
        action: 'index'

tablePanelProperties:

    headerLabel: 'Pages list'
    headerListButtons:
        create:
            buttonType: 'link'
            color: 'success'
            label: 'Add a page'
            action: 'create'
            modal: 'true'
            size: 'xs'

    tableFields:
        buttons:
            multipleFields:
            view:
                icon: 'eye'
                action: 'view'
                color: 'info'
                target: '_blank'
            update:
                icon: 'pencil'
                action: 'update'
            delete:
                icon: 'trash'
                color: 'danger'
                action: 'delete'
                confirm: 'Do you really want to delete this page ?'
        id:
        name: