title: 'Edit a page'

breadcrumb:
    index:
        label: 'Pages list'
        action: 'index'
    update:
        label: 'Edit a page'
        action: 'update'

formFields:
    name:
    title:
    resume:
    body:
    status:
    parent:
    menus:
    metas:
    pageTemplateSlug:
    saveAndStay:
        label: 'Save'
        type : 'submit'
    saveAndQuit:
        label: 'Save & Quit'
        type : 'submit'

central:
    tabs:
        contenu:
            name: 'Content'
            icon: 'file-text'
            formZones:
                entete:
                    title: 'Header'
                    fields:
                        name:
                            col: '6'
                        title:
                            col: '6'
                content:
                    title: 'Content'
                    fields:
                        resume:
                            col: '12'
                        body:
                            col: '12'
        metas:
            name: 'SEO'
            icon: 'google'
            formZones:
                seo:
                    fields:
                        metas.title:
                            col: '12'
                        metas.description:
                            col: '12'
                        metas.robots:
                            col: '12'
    viewLink:
        name: 'View'
        icon: 'eye'
        action: 'view'

column:
    panelZones:
        publication:
            headerLabel: 'Publication'
            icon: 'save'
            fields:
                - status
                - pageTemplateSlug
                - parent
                - menus
            footerListFormButtons:
                saveAndQuit:
                    field: 'saveAndQuit'
                    color: 'primary'
                saveAndStay:
                    field: 'saveAndStay'
                    color: 'success'
